#!/bin/bash

# Credit: https://stackoverflow.com/a/246128
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# ensure:
# 1) has a value
# 2) ends with slash (/)
if [[ "$1" == "" || "$1" != */ ]];
then
	echo "usage: add-SVNmentions-hook /path/to/svn-repo/ https://example.com/apache2/webspace/path"
	exit 1
fi

# ensure:
# 1) has a value
# 2) starts with http (for http:// or https://)
# 3) does NOT end with slash (/)
if [[ "$2" == "" || "$2" != http* || "$2" == */ ]];
then
	echo "usage: add-SVNmentions-hook /path/to/svn-repo/ https://example.com/apache2/webspace/path"
	exit 1
fi

if [ "$3" == "" ];
then
    CLIENT_ID=WebmentionsHook
else
    CLIENT_ID="$3"
fi

if [ "$4" == "" ];
then
    CLIENT_AGENT="SVNmentions (https://github.com/carrvo/SVNmentions-hook) curl/8.5.0"
else
    CLIENT_AGENT="$4"
fi

if [ "$5" == "" ];
then
    CLIENT_AUTHOR=SVNmention
else
    CLIENT_AUTHOR="$5"
fi

pushd "$1" > /dev/null
cd hooks/
echo installing post-commit in $PWD
if [ -f ./post-commit ]; then
   if [ -d ./post-commit.d/ ]; then
       ln -s /usr/src/SVNmentions-hook/post-commit ./post-commit.d/SVNmentions
    else
       echo "conflict!"
       exit 2
    fi
else
   ln -s /usr/src/SVNmentions-hook/post-commit post-commit
fi

cd ../conf/
echo installing post-commit environment variables in $PWD
echo "" >> $PWD/hooks-env
echo "[post-commit]" >> $PWD/hooks-env
echo "WebmentionsWebspaceRoot = $2" >> $PWD/hooks-env
echo "WebmentionsClientID = $CLIENT_ID" >> $PWD/hooks-env
echo "WebmentionsAuthor = $CLIENT_AUTHOR" >> $PWD/hooks-env
echo "WebmentionsAgent = $CLIENT_AGENT" >> $PWD/hooks-env
if [ ! -f $PWD/hooks-env ];
then
    echo "Please manually create hooks-env"
    echo "echo '' >> $PWD/hooks-env"
    echo "echo '[post-commit]' >> $PWD/hooks-env"
    echo "echo 'WebmentionsWebspaceRoot = $2' >> $PWD/hooks-env"
    echo "echo 'WebmentionsClientID = $CLIENT_ID' >> $PWD/hooks-env"
    echo "echo 'WebmentionsAuthor = $CLIENT_AUTHOR' >> $PWD/hooks-env"
    echo "echo 'WebmentionsAgent = $CLIENT_AGENT' >> $PWD/hooks-env"
fi
popd > /dev/null

