#!/usr/bin/php
<?php
// see https://svnbook.red-bean.com/en/1.8/svn.ref.reposhooks.post-commit.html
$repository_path = $argv[1]; // Repository path
$revision = $argv[2]; // Revision number created by the commit
$transaction = $argv[3]; // Name of the transaction that has become the revision triggering the post-commit hook.

$apache2_path = getenv('WebmentionsWebspaceRoot');
$client_id = getenv('WebmentionsClientID');
$webmentions_author = getenv('WebmentionsAuthor');
if (empty($webmentions_author) === true) {
    $webmentions_author = 'SVNmention';
}

function svnlook_cmd(string $subcmd, string $args): array|bool
{
    $cmd = "svnlook $subcmd $args";
    $output = null;
    $retval = null;
    $cmd_ran = exec($cmd, $output, $retval);
    if ($cmd_ran === false) {
        error_log("[SVNmentions-hook:info] SVN $subcmd failed to run");
        return false;
    }
    if ($retval !== 0) {
        error_log("[SVNmentions-hook:info] SVN $subcmd returned with status: $retval");
        return false;
    }
    return $output;
}

// see https://www.php.net/manual/en/class.domdocument.php
// see https://www.php.net/manual/en/class.domxpath.php

function stripReference(&$element, $key, $walk_arg)
{
    $uri = parse_url($element->getAttribute($walk_arg['attr']));
    // check whether external or must be on the same server as the sender
    $uri = array_replace($walk_arg['uri'], $uri); // use source as default values, replace with element values
    $build_uri = $uri['scheme'] . '://' . $uri['host'];
    if (isset($uri['port'])) {
        $build_uri .= ':' . $uri['port'];
    }
    $path = substr($uri['path'], 2);
    if (str_starts_with($uri['path'], '/')) {
        $build_uri .= $uri['path'];
    } elseif (str_starts_with($uri['path'], './')) {
        $build_uri .= dirname($walk_arg['uri']['path']) . '/' . $path;
    } elseif (str_starts_with($uri['path'], '../')) {
        $build_uri .= dirname($walk_arg['uri']['path'], 1) . '/' . $path;
    } else {
        // invalid
        return '';
    }
    if (isset($uri['query'])) {
        $build_uri .= '?' . $uri['query'];
    }
    if (isset($uri['fragment'])) {
        $build_uri .= '#' . $uri['fragment'];
    }
    $element = $build_uri;
}

function getDestinations(string $mime_path, string $source_content, string $source_uri): array|bool
{
    // see https://www.php.net/manual/en/function.include.php
    // especially example 5
    $destinations = include "$mime_path";
    return $destinations;
}

// see https://www.w3.org/TR/webmention/#sending-webmentions

function initCurl(string $url): CurlHandle|false
{
    global $client_id;
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($curl, CURLOPT_MAXREDIRS, 8);
    curl_setopt($curl, CURLOPT_TIMEOUT_MS, round(4 * 1000));
    curl_setopt($curl, CURLOPT_CONNECTTIMEOUT_MS, 2000);
    curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2);
    curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($curl, CURLOPT_USERNAME, $client_id);

    $agent = getenv('WebmentionsAgent');
    if ($agent === false) {
        $agent = 'SVNmentions (https://github.com/carrvo/SVNmentions-hook) curl/8.5.0';
    }
    curl_setopt($curl, CURLOPT_USERAGENT, "$agent");

    include "/usr/share/SVNmentions-hook/auth.php";

    return $curl;
}

function execAuthCurl(CurlHandle $curl, $url)
{
    global $client_id;

    $body = curl_exec($curl);
    $httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
    if ($httpcode !== 401) {
        return $body;
    }

    $agent = getenv('WebmentionsAgent');
    if ($agent === false) {
        $agent = 'SVNmentions (https://github.com/carrvo/SVNmentions-hook) curl/8.5.0';
    }

    $auth_type = curl_getinfo($curl, CURLINFO_HTTPAUTH_AVAIL);
    switch ($true) {
        case ($auth_type & CURLAUTH_BEARER !== 0):
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/bearer.php";
            break;
        case ($auth_type & CURLAUTH_DIGEST_IE !== 0):
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/digest_ie.php";
            break;
        case ($auth_type & CURLAUTH_DIGEST !== 0):
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/digest.php";
            break;
        case ($auth_type & CURLAUTH_NEGOTIATE !== 0):
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/negotiate.php";
            break;
        case ($auth_type & CURLAUTH_NTLM_WB !== 0):
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/ntlm_wb.php";
            break;
        case ($auth_type & CURLAUTH_NTLM !== 0):
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/ntlm.php";
            break;
        case ($auth_type & CURLAUTH_GSSNEGOTIATE !== 0):
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/gssnegotiate.php";
            break;
        case ($auth_type & CURLAUTH_GSSAPI !== 0):
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/gssapi.php";
            break;
        case ($auth_type & CURLAUTH_AWS_SIGV4 !== 0):
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/aws_sigv4.php";
            break;
        case ($auth_type & CURLAUTH_BASIC !== 0):
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/basic.php";
            break;
        default:
            $auth_plugin = "/usr/share/SVNmentions-hook/auth/default.php";
            break;
    }

    if (file_exists($auth_plugin) === true && is_dir($auth_plugin) === false) {
        echo "Using authentication plugin $auth_plugin"; // to be logged
        include $auth_plugin;
        $body = curl_exec($curl);
    }
    return $body;
}

function discoverWebmention($targetURI): string|bool
{
    $target = parse_url($targetURI);
    $curl = initCurl($targetURI);
    curl_setopt($curl, CURLOPT_HTTPHEADER, ['Accept: text/html']);
    curl_setopt($curl, CURLOPT_HEADER, true);
    $response = execAuthCurl($curl, $targetURI);
    $header_size = curl_getinfo($curl, CURLINFO_HEADER_SIZE);
    curl_close($curl);
    if (curl_errno($curl)) {
        fwrite(STDERR, "cURL error: " . curl_errno($curl) . "\n");
        return false;
    }
    // Credit: https://stackoverflow.com/a/9183272 (but there is a potentially better answer)
    $header = substr($response, 0, $header_size);
    $body = substr($response, $header_size);
    if (preg_match('/LINK: (http.*); rel="webmention"/', $header, $matches) === 1) {
        return $matches[1];
    }

    $dom = new DOMDocument();
    libxml_use_internal_errors(true); // Credit: https://stackoverflow.com/a/9149241
    $dom->loadHTML($body);
    libxml_use_internal_errors(false);
    $xpath = new DOMXpath($dom);
    $links = iterator_to_array($xpath->query("*/link[@rel='webmention']"));
    array_walk($links, 'stripReference', array('dom'=>$dom, 'uri'=>$target, 'attr'=>'href'));
    if (isset($links[0])) {
        return $links[0];
    }
    $anchors = iterator_to_array($xpath->query("*/a[@rel='webmention']"));
    array_walk($anchors, 'stripReference', array('dom'=>$dom, 'uri'=>$target, 'attr'=>'href'));
    if (isset($anchors[0])) {
        return $anchors[0];
    }
    return false;
}

function sendWebmention(string $sourceURI, string $targetURI, string $type = NULL, string $property = NULL): bool
{
    $webmention_endpoint = discoverWebmention($targetURI);
    if ($webmention_endpoint === false) {
        fwrite(STDERR, "webmention failure: could not discover receiver for $targetURI\n");
        return false;
    }
    echo "Sending Webmention from $sourceURI to $targetURI using $webmention_endpoint\n";

    $curl = initCurl($webmention_endpoint);
    curl_setopt($curl, CURLOPT_POST, true);
    if ($type === NULL || $property === NULL) {
        curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query(array('source' => $sourceURI, 'target' => $targetURI)));
    }
    else {
        curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query(array('source' => $sourceURI, 'target' => $targetURI, 'type' => $type, 'property' => $property)));
    }
    //curl_setopt($curl, CURLOPT_HEADER, true);
    $body = execAuthCurl($curl, $webmention_endpoint);
    $httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
    curl_close($curl);
    switch ($httpcode) {
        case 200:
        case 201:
        case 202:
            return true;
        default:
            fwrite(STDERR, "webmention failure $httpcode: $body\n");
            return false;
    }
}

// processing

function svnlook_trim($svnlook_result) {
    if ($svnlook_result === false) {
        return [];
    }
    return array_map('trim', array_slice($svnlook_result, 1));
}

try {
    $previous_revision = intval($revision) - 1;
    if ($previous_revision < 0) {
        $previous_revision = 0;
    }
    $anyFailure = false;
    $sender_paths = svnlook_cmd('changed', "-r '$revision' '$repository_path'");
    if ($sender_paths === false) {
        // nothing to inspect
        exit(0);
    }
    $commit_author = svnlook_cmd('author', "-r '$revision' '$repository_path'");
    if ($commit_author !== false && strcmp($commit_author[0], $webmentions_author) === 0) {
        // skip webmention receiver commits
        exit(0);
    }
    foreach ($sender_paths as $sender_path) {
        // remove 'U   ' preceding path
        $sender_path = substr($sender_path, 4);
        $sender_uri = "$apache2_path/$sender_path";
        $sender_properties = svnlook_trim(svnlook_cmd('proplist', "-r '$revision' '$repository_path' '$sender_path'"));
        $sender_previous_properties = svnlook_trim(svnlook_cmd('proplist', "-r '$previous_revision' '$repository_path' '$sender_path'"));

        $sender_skip = in_array('webmention:skip', $sender_properties) ? svnlook_cmd('propget', "-r '$revision' '$repository_path' webmention:skip '$sender_path'") : false;
        $sender_previous_skip = in_array('webmention:skip', $sender_previous_properties) ? svnlook_cmd('propget', "-r '$previous_revision' '$repository_path' webmention:skip '$sender_path'") : false;
        if ($sender_skip !== false) {
            // webmention:skip is set
            continue;
        }
        $sender_mime = in_array('svn:mime-type', $sender_properties) ? svnlook_cmd('propget', "-r '$revision' '$repository_path' svn:mime-type '$sender_path'") : false;
        if ($sender_mime === false) {
            // svn:mime-type not set
            continue;
        }
        $sender_mime = $sender_mime[0]; // should only have one value
        $sender_content = svnlook_cmd('cat', "-r '$revision' '$repository_path' '$sender_path'");
        $sender_previous_content = $sender_previous_skip === false ? svnlook_cmd('cat', "-r '$previous_revision' '$repository_path' '$sender_path'") : false;
        $destinations = [];
        $mime_path = realpath("/usr/share/SVNmentions-hook/mime/$sender_mime.php");
        // is sanitary and exists and file (not directory)
        if (preg_match("@/usr/share/SVNmentions-hook/mime/\w+/\w+.php@", $mime_path) === 1 && file_exists($mime_path) === true && is_dir($mime_path) === false) {
            if ($sender_previous_content !== false) {
                $destinations = array_merge($destinations, getDestinations($mime_path, implode("\n", $sender_previous_content), $sender_uri));
            }
            if ($sender_content !== false) {
                $destinations = array_merge($destinations, getDestinations($mime_path, implode("\n", $sender_content), $sender_uri));
            }
            // neither --> not a file?
        }
        else {
            $destinations = false;
        }
        if ($destinations !== false) {
            // destinations to webmention found in content
            foreach (array_unique($destinations) as $destination) {
                // do not send to `#header` destination links (self-referencing links)
                if (preg_match('/'.preg_quote($sender_uri, '/').'#/', $destination) !== 1) {
                    if (sendWebmention($sender_uri, $destination) === false) {
                        $anyFailure = true;
                    }
                }
            }
        }
        $sender_nonstandard = in_array('webmention:send', $sender_properties) ? svnlook_cmd('propget', "-r '$revision' '$repository_path' webmention:send '$sender_path'") : false;
        if ($sender_nonstandard !== false) {
            // destinations to webmention found in property webmention:send
            foreach ($sender_nonstandard as $destination) {
                // do not send to `#header` destination links (self-referencing links)
                if (preg_match('/'.preg_quote($sender_uri, '/').'#/', $destination) !== 1) {
                    if (sendWebmention($sender_uri, $destination, type: 'webdav', property: 'webmention:send') === false) {
                        $anyFailure = true;
                    }
                }
            }
        }
    }
} catch (Exception $ex) {
    fwrite(STDERR, "webmention failure: $ex\n");
    $anyFailure = true;
}
if ($anyFailure) {
    exit(-1);
}
?>
