#!/usr/bin/php
<?php
// see https://svnbook.red-bean.com/en/1.8/svn.ref.reposhooks.post-commit.html
$repository_path = $argv[1]; // Repository path
$revision = $argv[2]; // Revision number created by the commit
$transaction = $argv[3]; // Name of the transaction that has become the revision triggering the post-commit hook.

$apache2_path = rtrim(file_get_contents(dirname($argv[0]) . '/apache2.path'));
$client_id = rtrim(file_get_contents(dirname($argv[0]) . '/apache2.id'));
$webmentions_author = 'SVNmention'; // TODO: how to make this configurable

function svnlook_cmd(string $subcmd, string $args): array|bool
{
    $cmd = "svnlook $subcmd $args";
    $output = null;
    $retval = null;
    $cmd_ran = exec($cmd, $output, $retval);
    if ($cmd_ran === false) {
        error_log("[SVNmentions-hook:info] SVN $subcmd failed to run");
        return false;
    }
    if ($retval !== 0) {
        error_log("[SVNmentions-hook:info] SVN $subcmd returned with status: $retval");
        return false;
    }
    return $output;
}

// see https://www.php.net/manual/en/class.domdocument.php
// see https://www.php.net/manual/en/class.domxpath.php

function stripReference(&$element, $key, $walk_arg)
{
    $uri = parse_url($element->getAttribute($walk_arg['attr']));
    // check whether external or must be on the same server as the sender
    $uri = array_replace($walk_arg['uri'], $uri); // use source as default values, replace with element values
    $build_uri = $uri['scheme'] . '://' . $uri['host'];
    if (isset($uri['port'])) {
        $build_uri .= ':' . $uri['port'];
    }
    $path = substr($uri['path'], 2);
    if (str_starts_with($uri['path'], '/')) {
        $build_uri .= $uri['path'];
    } elseif (str_starts_with($uri['path'], './')) {
        $build_uri .= dirname($walk_arg['uri']['path']) . '/' . $path;
    } elseif (str_starts_with($uri['path'], '../')) {
        $build_uri .= dirname($walk_arg['uri']['path'], 1) . '/' . $path;
    } else {
        // invalid
        return '';
    }
    if (isset($uri['query'])) {
        $build_uri .= '?' . $uri['query'];
    }
    if (isset($uri['fragment'])) {
        $build_uri .= '#' . $uri['fragment'];
    }
    $element = $build_uri;
}

function getHTMLDestinations(string $source_content, string $source_uri): array|bool
{
    $source = parse_url($source_uri);
    $dom = new DOMDocument();
    libxml_use_internal_errors(true); // Credit: https://stackoverflow.com/a/9149241
    $dom->loadHTML($source_content);
    libxml_use_internal_errors(false);
    $webmention_section = $dom->getElementById('webmentions');
    if ($webmention_section instanceof DomElement) {
        $dom->removeChild($webmention_section); // do not include webmentions in the search
    }

    $xpath = new DOMXpath($dom);
    $hrefs = iterator_to_array($xpath->query('//*[@href]'));
    array_walk($hrefs, 'stripReference', array('dom'=>$dom, 'uri'=>$source, 'attr'=>'href'));
    $srcs = iterator_to_array($xpath->query('//*[@src]'));
    array_walk($srcs, 'stripReference', array('dom'=>$dom, 'uri'=>$source, 'attr'=>'src'));
    $references = array_merge($hrefs, $srcs);
    return $references;
}

// see https://www.w3.org/TR/webmention/#sending-webmentions

function initCurl(string $url): CurlHandle|false
{
    global $client_id;
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($curl, CURLOPT_MAXREDIRS, 8);
    curl_setopt($curl, CURLOPT_TIMEOUT_MS, round(4 * 1000));
    curl_setopt($curl, CURLOPT_CONNECTTIMEOUT_MS, 2000);
    curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2);
    curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($curl, CURLOPT_USERNAME, $client_id);
    return $curl;
}

function discoverWebmention($targetURI): string|bool
{
    $target = parse_url($targetURI);
    $curl = initCurl($targetURI);
    curl_setopt($curl, CURLOPT_HTTPHEADER, ['Accept: text/html']);
    curl_setopt($curl, CURLOPT_HEADER, true);
    $response = curl_exec($curl);
    $header_size = curl_getinfo($curl, CURLINFO_HEADER_SIZE);
    curl_close($curl);
    if (curl_errno($curl)) {
        fwrite(STDERR, "cURL error: " . curl_errno($curl) . "\n");
        return false;
    }
    // Credit: https://stackoverflow.com/a/9183272 (but there is a potentially better answer)
    $header = substr($response, 0, $header_size);
    $body = substr($response, $header_size);
    if (preg_match('/LINK: (http.*); rel="webmention"/', $header, $matches) === 1) {
        return $matches[1];
    }

    $dom = new DOMDocument();
    libxml_use_internal_errors(true); // Credit: https://stackoverflow.com/a/9149241
    $dom->loadHTML($body);
    libxml_use_internal_errors(false);
    $xpath = new DOMXpath($dom);
    $links = iterator_to_array($xpath->query("*/link[@rel='webmention']"));
    array_walk($links, 'stripReference', array('dom'=>$dom, 'uri'=>$target, 'attr'=>'href'));
    if (isset($links[0])) {
        return $links[0];
    }
    $anchors = iterator_to_array($xpath->query("*/a[@rel='webmention']"));
    array_walk($anchors, 'stripReference', array('dom'=>$dom, 'uri'=>$target, 'attr'=>'href'));
    if (isset($anchors[0])) {
        return $anchors[0];
    }
    return false;
}

function sendWebmention(string $sourceURI, string $targetURI, string $type = NULL, string $property = NULL): bool
{
    $webmention_endpoint = discoverWebmention($targetURI);
    if ($webmention_endpoint === false) {
        fwrite(STDERR, "webmention failure: could not discover receiver for $targetURI\n");
        return false;
    }
    echo "Sending Webmention from $sourceURI to $targetURI using $webmention_endpoint\n";

    $curl = initCurl($webmention_endpoint);
    curl_setopt($curl, CURLOPT_POST, true);
    if ($type === NULL || $property === NULL) {
        curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query(array('source' => $sourceURI, 'target' => $targetURI)));
    }
    else {
        curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query(array('source' => $sourceURI, 'target' => $targetURI, 'type' => $type, 'property' => $property)));
    }
    //curl_setopt($curl, CURLOPT_HEADER, true);
    $body = curl_exec($curl);
    $httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
    curl_close($curl);
    switch ($httpcode) {
        case 200:
        case 201:
        case 202:
            return true;
        default:
            fwrite(STDERR, "webmention failure: $body\n");
            return false;
    }
}

// processing

try {
    $anyFailure = false;
    $sender_paths = svnlook_cmd('changed', "-r '$revision' '$repository_path'");
    if ($sender_paths === false) {
        // nothing to inspect
        exit(0);
    }
    $commit_author = svnlook_cmd('author', "-r '$revision' '$repository_path'");
    if ($commit_author !== false && strcmp($commit_author[0], $webmentions_author) === 0) {
        // skip webmention receiver commits
        exit(0);
    }
    foreach ($sender_paths as $sender_path) {
        // remove 'U   ' preceding path
        $sender_path = substr($sender_path, 4);
        $sender_uri = "$apache2_path/$sender_path";
        $sender_skip = svnlook_cmd('propget', "-r '$revision' '$repository_path' webmention:skip '$sender_path'");
        if ($sender_skip !== false) {
            // webmention:skip is set
            continue;
        }
        $sender_mime = svnlook_cmd('propget', "-r '$revision' '$repository_path' svn:mime-type '$sender_path'");
        if ($sender_mime === false) {
            // svn:mime-type not set
            continue;
        }
        $sender_mime = $sender_mime[0]; // should only have one value
        $sender_content = svnlook_cmd('cat', "-r '$revision' '$repository_path' '$sender_path'");
        if ($sender_content === false) {
            // not a file?
            continue;
        }
        switch ("$sender_mime") {
            case 'text/html':
                $destinations = getHTMLDestinations(implode("\n", $sender_content), $sender_uri);
                break;
            default:
                $destinations = false;
                break;
        }
        if ($destinations !== false) {
            // destinations to webmention found in content
            foreach ($destinations as $destination) {
                // do not send to `#header` destination links (self-referencing links)
                if (preg_match('/'.preg_quote($sender_uri, '/').'#/', $destination) !== 1) {
                    if (sendWebmention($sender_uri, $destination) === false) {
                        $anyFailure = true;
                    }
                }
            }
        }
        $sender_nonstandard = svnlook_cmd('propget', "-r '$revision' '$repository_path' webmention:send '$sender_path'");
        if ($sender_nonstandard !== false) {
            // destinations to webmention found in property webmention:send
            foreach ($sender_nonstandard as $destination) {
                // do not send to `#header` destination links (self-referencing links)
                if (preg_match('/'.preg_quote($sender_uri, '/').'#/', $destination) !== 1) {
                    if (sendWebmention($sender_uri, $destination, type: 'webdav', property: 'webmention:send') === false) {
                        $anyFailure = true;
                    }
                }
            }
        }
    }
} catch (Exception $ex) {
    fwrite(STDERR, "webmention failure: $ex\n");
    $anyFailure = true;
}
if ($anyFailure) {
    exit(-1);
}
?>
